"""empty message

Revision ID: 182aedb166ea
Revises: 6f549d2f6804
Create Date: 2021-04-27 14:47:11.961208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182aedb166ea'
down_revision = '6f549d2f6804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=4096), nullable=True),
    sa.Column('lname', sa.String(length=4096), nullable=True),
    sa.Column('major', sa.String(length=4096), nullable=True),
    sa.Column('email', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignmentname', sa.String(length=4096), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    op.drop_table('students')
    # ### end Alembic commands ###
